typography_spectrum: 0.21243
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.27874657744541764
  lightness: 0.7154861728195101
  saturation: 0.26437044725753367
  rhythmicContrast: 0.5809660528320819
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6256317882798612
analytics:
  google: null
  facebook: null
  twitter: null
name: OneArtist
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Twitter
    url: 'https://twitter.com/oneartiststudio'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/justoneartist'
    type: external
favicon: null
coverPrefs:
  filter: false
purpose: []
