name: OneArtist
favicon: null
layout_spectrum: 0.75269
typography_spectrum: 0.21243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0702'
    - '#173034'
    - '#5f5a3a'
    - '#f8a82b'
    - '#0c6a80'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
