layout_spectrum: 0.3636797699145973
typography_spectrum: 0.19457273790612817
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.10374727053567767
  lightness: 0.5669889149721712
  saturation: 0.7876284865196794
  rhythmicContrast: 0.09196005063131452
coverPrefs:
  filter: false
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/4dc1b23a-6932-4b56-b1c9-824800233e4a.jpg
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ivan Schuler
  email: ivan@oneartiststudio.com
  url: www.oneartiststudio.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/21f1b973-fa63-4ad8-a096-d4c699e47cc0.jpg
name: OneArtistStudio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Twitter
    url: 'https://twitter.com/oneartiststudio'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/justoneartist'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c2e6f438-f8cb-4056-9165-21eac756aff5.jpg
title: OneArtistStudio
description: Ivan Schuler
purpose: []
