name: OneArtist
favicon: null
layout_spectrum: 0.6256317882798612
typography_spectrum: 0.21243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.27874657744541764
  lightness: 0.7154861728195101
  saturation: 0.26437044725753367
  rhythmicContrast: 0.5809660528320819
purpose: []
coverPrefs:
  filter: false
